#+title: CL-RRT
#+author: Masataro Asai
#+email: guicho2.71828@gmail.com

* CL-RRT - Common Lisp implementation of RRT (Rapidily exploring Random Tree)

RRT is a fast probabilistic multidimentional path-plannning algorithm
introduced by S.M.LaValle [fn:paper]. It now has a widespread use in robotics
and now able to handle the real time systems such as automatic car
driving AI. Also, it has various extentions and optimization methods
such as:

+ MP-RRT
+ RR-belief-tree
+ RRG
+ RRT*
+ St-RRT

[fn:paper] S.M. LaValle and J.J. Kuffner. Randomized kinodynamic
planning. /The International Journal of Robotics Research/, Vol. 20,
No. 5, pp. 378–400, 2001.

** Dependencies

This library is at least tested on implementation listed below:

+ SBCL 1.1.2 on X86-64 Linux  3.2.0-39-generic (author's environment)

Also, it depends on the following libraries:

+ ITERATE  ::
    Jonathan Amsterdam's iterator/gatherer/accumulator facility

+ ALEXANDRIA  ::
    Alexandria is a collection of portable public domain utilities.

+ CL-ANNOT by Tomohiro Matsuyama ::
    Python-like Annotation Syntax for Common Lisp

+ ANAPHORA  ::
    
** Installation

+ First grab the code with =git clone git@github.com:guicho271828/cl-rrt.git=
+ Put it in local-project folder
+ open slime REPL
+ =(ql:quickload :cl-rrt)= and the library will be installed along with all
  the dependencies

** Author

+ Masataro Asai (guicho2.71828@gmail.com)
+ Univ. Tokyo -> Grad. school of Tokyo University

* API

** Core functions and generic functions

** Tree classes

** Helper functions

*** Path and tree walking

*** Node manipulation
* Copyright

Copyright (c) 2013 Masataro Asai (guicho2.71828@gmail.com)


* License

Licensed under the LLGPL License.

